name: sfm
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - biopython=1.83
  - dm-tree
  - loguru
  - mendeleev
  - networkx
  - ogb
  - peft
  - pybind11
  - python-lmdb
  - rdkit=2024.03.1
  - sentencepiece
  - setuptools-scm
  - tensorboard
  - transformers=4.40.1
  - wandb
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch=2.3.0=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch::torchaudio=2.3.0=py311_cu121
  - pytorch::torchvision=0.18.0=py311_cu121
  - defaults::cython
  - bioconda::tmalign
  - bioconda::lddt
  - pip:
      # torch-geometric and additional libs from pyg
      - torch-geometric==2.5.3
      # Note that pyg_lib, torch_scatter, torch_sparse, torch_cluster, torch_spline_conv should all be installed separately using --no-index. Run setup.sh to do so.
      # others
      - deepspeed==0.14.0
      - sacremoses==0.1.1
      - torch-tb-profiler==0.4.3
      - hydra-core
      - e3nn
      - fairchem-core==1.2.0
      - ase
      - nvidia-dali-cuda120
      - peft==0.13.2
